# Generated by Django 2.2.3 on 2019-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=100)),
                ('heading1', models.CharField(default='', max_length=100)),
                ('heading2', models.CharField(default='', max_length=150)),
                ('content1', models.TextField(default='', max_length=2500)),
                ('content2', models.TextField(default='', max_length=2500)),
                ('links', models.CharField(default='', max_length=500)),
                ('catagory', models.CharField(default='', max_length=30)),
                ('time', models.DateTimeField()),
                ('images', models.ImageField(default='', upload_to='thenation/images')),
                ('thumbnils', models.ImageField(default='', upload_to='thenation/images')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField(default=0)),
                ('query', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(default='', upload_to='thenation/images')),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
