# Generated by Django 2.2.3 on 2019-07-30 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(default='', upload_to='thenation/images')),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSpots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('heading1', models.CharField(default='', max_length=100)),
                ('heading2', models.CharField(default='', max_length=150)),
                ('content1', models.TextField(default='', max_length=500)),
                ('content2', models.TextField(default='', max_length=500)),
                ('links', models.CharField(default='', max_length=500)),
                ('catagory', models.CharField(default='', max_length=30)),
                ('time', models.DateTimeField()),
                ('images', models.ImageField(default='', upload_to='thenation/images')),
                ('thumbnils', models.ImageField(default='', upload_to='thenation/images')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
